/*
 * generated by Xtext 2.24.0
 */
package com.intuit.graphql.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GraphQLUiModule extends AbstractGraphQLUiModule {

	public GraphQLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
