/*
 * generated by Xtext 2.19.0
 */
package com.intuit.graphql


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GraphQLRuntimeModule extends AbstractGraphQLRuntimeModule {
}
