/*
 * generated by Xtext 2.30.0
 */
package com.intuit.graphql;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GraphQLStandaloneSetup extends GraphQLStandaloneSetupGenerated {

	public static void doSetup() {
		new GraphQLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
