/*
 * generated by Xtext 2.24.0
 */
package com.intuit.graphql.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.intuit.graphql.GraphQLRuntimeModule;
import com.intuit.graphql.GraphQLStandaloneSetup;
import com.intuit.graphql.ide.GraphQLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class GraphQLWebSetup extends GraphQLStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GraphQLRuntimeModule(), new GraphQLIdeModule(), new GraphQLWebModule()));
	}
	
}
