/*
 * generated by Xtext 2.28.0
 */
package com.intuit.graphql.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class GraphQLWebModule extends AbstractGraphQLWebModule {
}
