/*
 * generated by Xtext 2.19.0
 */
package com.intuit.graphql.ide

import com.google.inject.Guice
import com.intuit.graphql.GraphQLRuntimeModule
import com.intuit.graphql.GraphQLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class GraphQLIdeSetup extends GraphQLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new GraphQLRuntimeModule, new GraphQLIdeModule))
	}
	
}
