# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Master Build and Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
                  
      - name: Publish Snapshot to OSS Maven Repository
        if: ${{ github.ref == 'refs/heads/master' }}
        run: mvn -B --batch-mode deploy --file pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: jacoco-reports/target/site/jacoco-aggregate
          name: codecov-master
          verbose: true           
